name: lint-build
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  linter:
    uses: leboncoin/spark-ios-common/.github/workflows/linter.yml@main
  buildDemo:
    uses: leboncoin/spark-ios-demo/.github/workflows/buildDemo.yml@main
